Update patch set 1
Patch Set 1:

java.lang.RuntimeException: Unable to get provider com.android.providers.media.MediaProvider: java.lang.ArrayIndexOutOfBoundsException: src.length=4 srcPos=0 dst.length=4 dstPos=1 length=4
        at android.app.ActivityThread.installProvider(ActivityThread.java:7173)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6651)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6546)
        at android.app.ActivityThread.access$1400(ActivityThread.java:225)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1890)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=4 srcPos=0 dst.length=4 dstPos=1 length=4
        at java.lang.System.arraycopy(Native Method)
        at android.util.ArraySet.add(ArraySet.java:446)
        at com.android.providers.media.MediaProvider.<init>(MediaProvider.java:6365)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7157)
        ... 10 more

Patch-set: 1